# Generated by Django 3.0.2 on 2020-01-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='beer', max_length=100),
            preserve_default=False,
        ),
    ]
