# Generated by Django 3.0.2 on 2020-02-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200218_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.OneToOneField(default=21, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
            preserve_default=False,
        ),
    ]
