# Generated by Django 3.0.2 on 2020-02-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200218_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
    ]
